INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Walmart', 'WMT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Amazon', 'AMZN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Apple', 'AAPL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('UnitedHealth Group', 'UNH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Berkshire Hathaway', 'BRKA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CVS Health', 'CVS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Exxon Mobil', 'XOM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alphabet', 'GOOGL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('McKesson', 'MCK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cencora', 'COR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Costco Wholesale', 'COST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('JPMorgan Chase', 'JPM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Microsoft', 'MSFT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cardinal Health', 'CAH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chevron', 'CVX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cigna', 'CI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ford Motor', 'F');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bank of America', 'BAC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('General Motors', 'GM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Elevance Health', 'ELV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Citigroup', 'C');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Centene', 'CNC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Home Depot', 'HD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Marathon Petroleum', 'MPC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kroger', 'KR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Phillips 66', 'PSX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fannie Mae', 'FNMA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Walgreens Boots Alliance', 'WBA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Valero Energy', 'VLO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Meta Platforms', 'META');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Verizon Communications', 'VZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AT&T', 'T');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Comcast', 'CMCSA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Wells Fargo', 'WFC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Goldman Sachs Group', 'GS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Freddie Mac', 'FMCC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Target', 'TGT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Humana', 'HUM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tesla', 'TSLA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Morgan Stanley', 'MS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Johnson & Johnson', 'JNJ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Archer Daniels Midland', 'ADM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PepsiCo', 'PEP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('United Parcel Service', 'UPS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('FedEx', 'FDX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Walt Disney', 'DIS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dell Technologies', 'DELL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lowe''s', 'LOW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Procter & Gamble', 'PG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Energy Transfer', 'ET');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Boeing', 'BA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Albertsons', 'ACI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sysco', 'SYY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('RTX', 'RTX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('General Electric', 'GE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lockheed Martin', 'LMT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Express', 'AXP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Caterpillar', 'CAT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MetLife', 'MET');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('HCA Healthcare', 'HCA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Progressive', 'PGR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('IBM', 'IBM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Deere', 'DE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nvidia', 'NVDA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('StoneX Group', 'SNEX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Merck', 'MRK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ConocoPhillips', 'COP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pfizer', 'PFE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Delta Air Lines', 'DAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TD Synnex', 'SNX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Allstate', 'ALL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cisco Systems', 'CSCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Charter Communications', 'CHTR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AbbVie', 'ABBV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Intel', 'INTC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TJX', 'TJX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Prudential Financial', 'PRU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('HP', 'HPQ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('United Airlines Holdings', 'UAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Performance Food Group', 'PFGC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tyson Foods', 'TSN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Airlines Group', 'AAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nike', 'NKE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Oracle', 'ORCL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Enterprise Products Partners', 'EPD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Capital One Financial', 'COF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Plains GP Holdings', 'PAGP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('World Kinect', 'WKC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AIG', 'AIG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coca-Cola', 'KO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bristol-Myers Squibb', 'BMY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dow', 'DOW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Best Buy', 'BBY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Thermo Fisher Scientific', 'TMO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('General Dynamics', 'GD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Travelers', 'TRV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Warner Bros. Discovery', 'WBD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('U.S. Bancorp', 'USB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Abbott Laboratories', 'ABT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Northrop Grumman', 'NOC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dollar General', 'DG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PBF Energy', 'PBF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Uber Technologies', 'UBER');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Honeywell International', 'HON');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mondelez International', 'MDLZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Starbucks', 'SBUX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Qualcomm', 'QCOM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Broadcom', 'AVGO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('US Foods Holding', 'USFD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('D.R. Horton', 'DHI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Philip Morris International', 'PM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Paccar', 'PCAR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Salesforce', 'CRM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nucor', 'NUE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Jabil', 'JBL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lennar', 'LEN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Eli Lilly', 'LLY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Molina Healthcare', 'MOH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cummins', 'CMI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bank of New York Mellon', 'BK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Netflix', 'NFLX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Truist Financial', 'TFC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Arrow Electronics', 'ARW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('3M', 'MMM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Visa', 'V');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Apollo Global Management', 'APO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('HF Sinclair', 'DINO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CBRE Group', 'CBRE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PNC Financial Services Group', 'PNC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lithia Motors', 'LAD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CarMax', 'KMX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Paramount Global', 'PARA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dollar Tree', 'DLTR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('United Natural Foods', 'UNFI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PayPal Holdings', 'PYPL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Penske Automotive Group', 'PAG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hewlett Packard Enterprise', 'HPE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Duke Energy', 'DUK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Occidental Petroleum', 'OXY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NRG Energy', 'NRG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Amgen', 'AMGN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NextEra Energy', 'NEE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Danaher', 'DHR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Gilead Sciences', 'GILD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AutoNation', 'AN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kraft Heinz', 'KHC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Avnet', 'AVT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Applied Materials', 'AMAT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Southwest Airlines', 'LUV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Charles Schwab', 'SCHW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Baker Hughes', 'BKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('McDonald''s', 'MCD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Southern Company', 'SO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mastercard', 'MA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Constellation Energy', 'CEG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hartford Financial Services Group', 'HIG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PG&E', 'PCG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coupang', 'CPNG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EOG Resources', 'EOG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Union Pacific', 'UNP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rite Aid', 'RADCQ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Macy''s', 'M');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Marriott International', 'MAR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lear', 'LEA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Genuine Parts', 'GPC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sherwin-Williams', 'SHW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Halliburton', 'HAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Freeport-McMoRan', 'FCX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Live Nation Entertainment', 'LYV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Marsh & McLennan', 'MMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Advanced Micro Devices', 'AMD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('First Citizens BancShares', 'FCNCA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('WESCO International', 'WCC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Carrier Global', 'CARR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cleveland-Cliffs', 'CLF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Block', 'SQ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Exelon', 'EXC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('KKR', 'KKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CDW', 'CDW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Booking Holdings', 'BKNG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Synchrony', 'SYF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Quanta Services', 'PWR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Jones Lang LaSalle', 'JLL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Discover Financial Services', 'DFS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tenet Healthcare', 'THC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Altria Group', 'MO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Stryker', 'SYK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kimberly-Clark', 'KMB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Waste Management', 'WM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cheniere Energy', 'LNG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ross Stores', 'ROST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('General Mills', 'GIS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Goodyear Tire & Rubber', 'GT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BJ''s Wholesale Club', 'BJ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('GE HealthCare Technologies', 'GEHC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Colgate-Palmolive', 'CL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Whirlpool', 'WHR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('L3Harris Technologies', 'LHX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Adobe', 'ADBE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Becton Dickinson', 'BDX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pioneer Natural Resources', 'PXD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cognizant Technology Solutions', 'CTSH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Murphy USA', 'MUSA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fiserv', 'FI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Parker-Hannifin', 'PH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Electric Power', 'AEP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('International Paper', 'IP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ManpowerGroup', 'MAN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Aramark', 'ARMK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Steel Dynamics', 'STLD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Aflac', 'AFL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Reinsurance Group of America', 'RGA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Emerson Electric', 'EMR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('State Street', 'STT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PPG Industries', 'PPG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('United States Steel', 'X');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Automatic Data Processing', 'ADP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Group 1 Automotive', 'GPI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dominion Energy', 'D');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BlackRock', 'BLK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Oneok', 'OKE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('C.H. Robinson Worldwide', 'CHRW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Texas Instruments', 'TXN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kohl''s', 'KSS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AutoZone', 'AZO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lam Research', 'LRCX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Corteva', 'CTVA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Builders FirstSource', 'BLDR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kyndryl Holdings', 'KD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EchoStar', 'SATS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Delek US Holdings', 'DK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sempra', 'SRE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Global Partners', 'GLP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Grainger', 'GWW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Jacobs Solutions', 'J');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Edison International', 'EIX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MGM Resorts International', 'MGM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Illinois Tool Works', 'ITW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ameriprise Financial', 'AMP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PulteGroup', 'PHM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Targa Resources', 'TRGP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ally Financial', 'ALLY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BorgWarner', 'BWA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Estée Lauder', 'EL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Loews', 'L');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('O''Reilly Automotive', 'ORLY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Markel Group', 'MKL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Stanley Black & Decker', 'SWK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Micron Technology', 'MU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fluor', 'FLR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Leidos Holdings', 'LDOS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Viatris', 'VTRS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kinder Morgan', 'KMI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ecolab', 'ECL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Baxter International', 'BAX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Devon Energy', 'DVN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kellanova', 'K');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Casey''s General Stores', 'CASY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('IQVIA Holdings', 'IQV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Republic Services', 'RSG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fox', 'FOXA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Gap', 'GPS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Keurig Dr Pepper', 'KDP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Reliance', 'RS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Asbury Automotive Group', 'ABG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vistra', 'VST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Andersons', 'ANDE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nordstrom', 'JWN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Omnicom Group', 'OMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fidelity National Information Services', 'FIS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Consolidated Edison', 'ED');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CSX', 'CSX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AECOM', 'ACM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lumen Technologies', 'LUMN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tractor Supply', 'TSCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DXC Technology', 'DXC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AGCO', 'AGCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sonic Automotive', 'SAH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Intuit', 'INTU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('United Rentals', 'URI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Universal Health Services', 'UHS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Boston Scientific', 'BSX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Otis Worldwide', 'OTIS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Xcel Energy', 'XEL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ball', 'BALL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('LKQ', 'LKQ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mosaic', 'MOS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Textron', 'TXT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Labcorp Holdings', 'LH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Principal Financial', 'PFG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Regeneron Pharmaceuticals', 'REGN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Raymond James Financial', 'RJF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dick''s Sporting Goods', 'DKS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Expedia Group', 'EXPE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('J.B. Hunt Transport Services', 'JBHT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('M&T Bank', 'MTB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DTE Energy', 'DTE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AES', 'AES');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Berry Global Group', 'BERY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fifth Third Bancorp', 'FITB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Air Products & Chemicals', 'APD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Corning', 'GLW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EMCOR Group', 'EME');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Amphenol', 'APH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Westlake', 'WLK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DuPont', 'DD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Liberty Media', 'LSXMA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('S&P Global', 'SPGI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Community Health Systems', 'CYH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('FirstEnergy', 'FE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Unum Group', 'UNM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Henry Schein', 'HSIC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Western Digital', 'WDC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Analog Devices', 'ADI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Conagra Brands', 'CAG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Citizens Financial Group', 'CFG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Norfolk Southern', 'NSC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Entergy', 'ETR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('W.R. Berkley', 'WRB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DaVita', 'DVA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Northern Trust', 'NTRS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hormel Foods', 'HRL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Crown Holdings', 'CCK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Avis Budget Group', 'CAR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Wayfair', 'W');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MasTec', 'MTZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Eversource Energy', 'ES');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Newmont', 'NEM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ryder System', 'R');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fidelity National Financial', 'FNF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Molson Coors Beverage', 'TAP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Caesars Entertainment', 'CZR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lincoln National', 'LNC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('VF', 'VFC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('International Flavors & Fragrances', 'IFF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Huntington Ingalls Industries', 'HII');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Advance Auto Parts', 'AAP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Public Service Enterprise Group', 'PEG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ulta Beauty', 'ULTA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hershey', 'HSY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chewy', 'CHWY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Tower', 'AMT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mohawk Industries', 'MHK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Assurant', 'AIZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Thor Industries', 'THO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Yum China Holdings', 'YUMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Celanese', 'CE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Qurate Retail', 'QRTEA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Williams', 'WMB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Interpublic Group', 'IPG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ovintiv', 'OVV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Icahn Enterprises', 'IEP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Huntington Bancshares', 'HBAN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Carvana', 'CVNA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hess', 'HES');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dana', 'DAN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alcoa', 'AA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Equitable Holdings', 'EQH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('KLA', 'KLAC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Darden Restaurants', 'DRI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Autoliv', 'ALV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alaska Air Group', 'ALK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('KeyCorp', 'KEY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Las Vegas Sands', 'LVS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Owens & Minor', 'OMI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hilton Worldwide Holdings', 'HLT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ebay', 'EBAY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Arthur J. Gallagher', 'AJG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('LPL Financial Holdings', 'LPLA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cincinnati Financial', 'CINF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Toll Brothers', 'TOL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Motorola Solutions', 'MSI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Airbnb', 'ABNB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Intercontinental Exchange', 'ICE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('News Corp.', 'NWSA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chipotle Mexican Grill', 'CMG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vertex Pharmaceuticals', 'VRTX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Biogen', 'BIIB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('GXO Logistics', 'GXO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('SpartanNash', 'SPTN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Burlington Stores', 'BURL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NVR', 'NVR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Owens Corning', 'OC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Westinghouse Air Brake Technologies', 'WAB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Oshkosh', 'OSK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Global Payments', 'GPN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lululemon athletica', 'LULU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Albemarle', 'ALB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('JetBlue Airways', 'JBLU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Seaboard', 'SEB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Constellation Brands', 'STZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Graphic Packaging Holding', 'GPK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hertz Global Holdings', 'HTZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Campbell Soup', 'CPB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Expeditors Intl. of Washington', 'EXPD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('A-Mark Precious Metals', 'AMRK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Booz Allen Hamilton Holding', 'BAH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Quest Diagnostics', 'DGX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Altice USA', 'ATUS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PVH', 'PVH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Eastman Chemical', 'EMN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Insight Enterprises', 'NSIT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Regions Financial', 'RF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Beacon Roofing Supply', 'BECN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rockwell Automation', 'ROK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Polaris', 'PII');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ServiceNow', 'NOW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sanmina', 'SANM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('UGI', 'UGI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('WEC Energy Group', 'WEC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BrightSpring Health Services', 'BGST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cintas', 'CTAS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Commercial Metals', 'CMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Continental Resources', 'CLR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chesapeake Energy', 'CHK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CenterPoint Energy', 'CNP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NGL Energy Partners', 'NGL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DoorDash', 'DASH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NOV', 'NOV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Zoetis', 'ZTS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('J.M. Smucker', 'SJM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Microchip Technology', 'MCHP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dover', 'DOV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Diamondback Energy', 'FANG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Avery Dennison', 'AVY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PPL', 'PPL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ON Semiconductor', 'ON');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ARKO', 'ARKO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Par Pacific Holdings', 'PARR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('APA', 'APA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Equinix', 'EQIX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('New York Community Bancorp', 'NYCB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Foot Locker', 'FL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ingredion', 'INGR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Newell Brands', 'NWL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ABM Industries', 'ABM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Prologis', 'PLD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Blackstone', 'BX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Skechers U.S.A.', 'SKX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Masco', 'MAS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rush Enterprises', 'RUSHB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Franklin Resources', 'BEN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ODP', 'ODP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Financial Group', 'AFG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Packaging Corp. of America', 'PKG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vulcan Materials', 'VMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Interactive Brokers Group', 'IBKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Williams-Sonoma', 'WSM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('XPO', 'XPO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Weyerhaeuser', 'WY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Genworth Financial', 'GNW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CMS Energy', 'CMS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Science Applications International', 'SAIC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Jefferies Financial Group', 'JEF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bath & Body Works', 'BBWI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Electronic Arts', 'EA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Taylor Morrison Home', 'TMHC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Zimmer Biomet Holdings', 'ZBH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Clorox', 'CLX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Xylem', 'XYL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Voya Financial', 'VOYA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fastenal', 'FAST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Watsco', 'WSO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Workday', 'WDAY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Old Republic International', 'ORI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('RPM International', 'RPM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('UFP Industries', 'UFPI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ameren', 'AEE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Knight-Swift Transportation Hldgs.', 'KNX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Monster Beverage', 'MNST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Intuitive Surgical', 'ISRG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Super Micro Computer', 'SMCI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Concentrix', 'CNXC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('O-I Glass', 'OI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Yum Brands', 'YUM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CommScope Holding', 'COMM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Post Holdings', 'POST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Crown Castle', 'CCI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Avantor', 'AVTR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('KBR', 'KBR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Opendoor Technologies', 'OPEN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('APi Group', 'APG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EQT', 'EQT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EnLink Midstream', 'ENLC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Palo Alto Networks', 'PANW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Xerox Holdings', 'XRX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ingersoll Rand', 'IR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dillard''s', 'DDS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Martin Marietta Materials', 'MLM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vertiv Holdings', 'VRT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Moderna', 'MRNA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Boise Cascade', 'BCC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sprouts Farmers Market', 'SFM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Agilent Technologies', 'A');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Olin', 'OLN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Darling Ingredients', 'DAR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sonoco Products', 'SON');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CACI International', 'CACI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Core & Main', 'CNM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Marathon Oil', 'MRO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hyatt Hotels', 'H');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Select Medical Holdings', 'SEM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('McCormick', 'MKC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tapestry', 'TPR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coca-Cola Consolidated', 'COKE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Howmet Aerospace', 'HWM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Welltower', 'WELL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CF Industries Holdings', 'CF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ametek', 'AME');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TransDigm Group', 'TDG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Wynn Resorts', 'WYNN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Southwestern Energy', 'SWN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Amkor Technology', 'AMKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Insperity', 'NSP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Patterson', 'PDCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('T. Rowe Price', 'TROW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ralph Lauren', 'RL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('KB Home', 'KBH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brunswick', 'BC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Robert Half', 'RHI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PENN Entertainment', 'PENN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NetApp', 'NTAP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Organon', 'OGN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Petco Health and Wellness', 'WOOF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Regal Rexnord', 'RRX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Resideo Technologies', 'REZI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Camping World Holdings', 'CWH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Huntsman', 'HUN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Victoria''s Secret', 'VSCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Levi Strauss', 'LEVI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Roper Technologies', 'ROP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Academy Sports and Outdoors', 'ASO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Meritage Homes', 'MTH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Axle & Manufacturing', 'AXL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fortive', 'FTV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nasdaq', 'NDAQ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Broadridge Financial Solutions', 'BR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Spirit AeroSystems Holdings', 'SPR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Warner Music Group', 'WMG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chemours', 'CC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ADT', 'ADT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Edwards Lifesciences', 'EW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('First American Financial', 'FAF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hanover Insurance Group', 'THG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Silgan Holdings', 'SLGN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Endeavor Group Holdings', 'EDR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Moody''s', 'MCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coterra Energy', 'CTRA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Gartner', 'IT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Under Armour', 'UAA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ingles Markets', 'IMKTA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Church & Dwight', 'CHD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Old Dominion Freight Line', 'ODFL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('U-Haul Holding', 'UHAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Oscar Health', 'OSCR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Arista Networks', 'ANET');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Synopsys', 'SNPS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Harley-Davidson', 'HOG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Frontier Communications', 'FYBR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Primoris Services', 'PRIM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Carlisle', 'CSL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Simon Property Group', 'SPG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hanesbrands', 'HBI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Anywhere Real Estate', 'HOUS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Teledyne Technologies', 'TDY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CME Group', 'CME');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Juniper Networks', 'JNPR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coty', 'COTY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pool', 'POOL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Evergy', 'EVRG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Marvell Technology', 'MRVL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NiSource', 'NI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('SS&C Technologies Holdings', 'SSNC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Schneider National', 'SNDR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Autodesk', 'ADSK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sealed Air', 'SEE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Iron Mountain', 'IRM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Digital Realty Trust', 'DLR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Keysight Technologies', 'KEYS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Globe Life', 'GL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Parsons', 'PSN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mattel', 'MAT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Southwest Gas Holdings', 'SWX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Clean Harbors', 'CLH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hubbell', 'HUBB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Spirit Airlines', 'SAVE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lamb Weston Holdings', 'LW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Take-Two Interactive Software', 'TTWO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('GMS', 'GMS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Landstar System', 'LSTR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Host Hotels & Resorts', 'HST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fortinet', 'FTNT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('OneMain Holdings', 'OMF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('GameStop', 'GME');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Equifax', 'EFX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Eagle Outfitters', 'AEO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Comerica', 'CMA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Greif', 'GEF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Comfort Systems USA', 'FIX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TopBuild', 'BLD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bread Financial Holdings', 'BFH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coherent', 'COHR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Telephone & Data Systems', 'TDS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Stifel Financial', 'SF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Urban Outfitters', 'URBN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Terex', 'TEX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ryerson Holding', 'RYI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Snap-on', 'SNA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Flowers Foods', 'FLO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('First Horizon', 'FHN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Paychex', 'PAYX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hasbro', 'HAS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ares Management', 'ARES');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lennox International', 'LII');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Peabody Energy', 'BTU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kemper', 'KMPR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nexstar Media Group', 'NXST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tempur Sealy International', 'TPX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TriNet Group', 'TNET');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Worthington Enterprises', 'WOR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Maximus', 'MMS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Compass', 'COMP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brink''s', 'BCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kelly Services', 'KELYA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Navient', 'NAVI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AMC Entertainment Holdings', 'AMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Encompass Health', 'EHC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Skyworks Solutions', 'SWKS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Timken', 'TKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Liberty Energy', 'LBRT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Marriott Vacations Worldwide', 'VAC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Leggett & Platt', 'LEG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Big Lots', 'BIG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Weis Markets', 'WMK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pinnacle West Capital', 'PNW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EPAM Systems', 'EPAM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Antero Resources', 'AR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bloomin'' Brands', 'BLMN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MDU Resources Group', 'MDU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Texas Roadhouse', 'TXRH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mercury General', 'MCY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Fortune Brands Innovations', 'FBIN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Zions Bancorp.', 'ZION');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('JELD-WEN Holding', 'JELD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Snap', 'SNAP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Zebra Technologies', 'ZBRA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Agilon Health', 'AGL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Toro', 'TTC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Zoom Video Communications', 'ZM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tetra Tech', 'TTEK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Public Storage', 'PSA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Illumina', 'ILMN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ventas', 'VTR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('FMC', 'FMC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ArcBest', 'ARCB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Domino''s Pizza', 'DPZ');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ASGN', 'ASGN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rivian Automotive', 'RIVN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Elanco Animal Health', 'ELAN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Graham Holdings', 'GHC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Floor & Decor Holdings', 'FND');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Applied Industrial Technologies', 'AIT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PriceSmart', 'PSMT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lyft', 'LYFT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ciena', 'CIEN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('IAC', 'IAC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Western Union', 'WU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Flowserve', 'FLS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Western Alliance Bancorp.', 'WAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Option Care Health', 'OPCH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('SiteOne Landscape Supply', 'SITE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Topgolf Callaway Brands', 'MODG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('eXp World Holdings', 'EXPI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Abercrombie & Fitch', 'ANF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Atmos Energy', 'ATO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Catalent', 'CTLT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brown & Brown', 'BRO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('GoDaddy', 'GDDY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American Water Works', 'AWK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Selective Insurance Group', 'SIGI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brown-Forman', 'BF.B');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Advantage Solutions', 'ADV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ResMed', 'RMD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Plexus', 'PLXS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hub Group', 'HUBG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Lincoln Electric Holdings', 'LECO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NCR Atleos', 'NATL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Calumet', 'CLMT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dycom Industries', 'DY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Valmont Industries', 'VMI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ATI', 'ATI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Twilio', 'TWLO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CNO Financial Group', 'CNO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Patterson-UTI Energy', 'PTEN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brinker International', 'EAT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Charles River Laboratories International', 'CRL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hyster-Yale', 'HY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brighthouse Financial', 'BHF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Service Corp. International', 'SCI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CrossAmerica Partners', 'CAPL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cadence', 'CDNS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MillerKnoll', 'MLKN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Realty Income', 'O');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Middleby', 'MIDD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('M/I Homes', 'MHO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hologic', 'HOLX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alliant Energy', 'LNT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Generac Holdings', 'GNRC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MSC Industrial Direct', 'MSM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rocket Companies', 'RKT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Upbound Group', 'UPBD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('East West Bancorp', 'EWBC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hilton Grand Vacations', 'HGV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Grocery Outlet Holding', 'GO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dentsply Sirona', 'XRAY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('V2X', 'VVX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Crocs', 'CROX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Spectrum Brands Holdings', 'SPB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Visteon', 'VC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Acuity Brands', 'AYI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Greenbrier', 'GBX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Webster Financial', 'WBS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cabot', 'CBT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('RXO', 'RXO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chord Energy', 'CHRD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Popular', 'BPOP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Garrett Motion', 'GTX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tutor Perini', 'TPC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Copart', 'CPRT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Toast', 'TOST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Align Technology', 'ALGN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('A.O. Smith', 'AOS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TransUnion', 'TRU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NCR Voyix', 'VYX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Akamai Technologies', 'AKAM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Trimble', 'TRMB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AMN Healthcare Services', 'AMN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mettler-Toledo International', 'MTD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ScanSource', 'SCSC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('LCI Industries', 'LCII');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cboe Global Markets', 'CBOE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Diebold Nixdorf', 'DBD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ChampionX', 'CHX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Corpay', 'CPAY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('iHeartMedia', 'IHRT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Travel + Leisure', 'TNL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dream Finders Homes', 'DFH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Boyd Gaming', 'BYD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Ensign Group', 'ENSG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sally Beauty Holdings', 'SBH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Conduent', 'CNDT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sylvamo', 'SLVM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Tri Pointe Homes', 'TPH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('EnerSys', 'ENS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Incyte', 'INCY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Century Communities', 'CCS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rithm Capital', 'RITM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Euronet Worldwide', 'EEFT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hawaiian Electric Industries', 'HE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DraftKings', 'DKNG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('IDEXX Laboratories', 'IDXX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MYR Group', 'MYRG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Deckers Outdoor', 'DECK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DexCom', 'DXCM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MKS Instruments', 'MKSI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('VICI Properties', 'VICI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cooper Cos.', 'COO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Frontier Group Holdings', 'ULCC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Qorvo', 'QRVO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Five Below', 'FIVE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TreeHouse Foods', 'THS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Scotts Miracle-Gro', 'SMG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Atlassian', 'TEAM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Entegris', 'ENTG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Atkore', 'ATKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('H.B. Fuller', 'FUL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Granite Construction', 'GVA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Winnebago Industries', 'WGO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('FTI Consulting', 'FCN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AptarGroup', 'ATR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Columbia Sportswear', 'COLM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Roku', 'ROKU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Civitas Resources', 'CIVI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('H&R Block', 'HRB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alpha Metallurgical Resources', 'AMR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Patrick Industries', 'PATK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Murphy Oil', 'MUR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Synovus Financial', 'SNV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cracker Barrel Old Country Store', 'CBRL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cheesecake Factory', 'CAKE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CNX Resources', 'CNX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chefs'' Warehouse', 'CHEF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Donaldson', 'DCI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mueller Industries', 'MLI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MRC Global', 'MRC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Chart Industries', 'GTLS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alight', 'ALIT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vishay Intertechnology', 'VSH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Range Resources', 'RRC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Valley National Bancorp', 'VLY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Match Group', 'MTCH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Gen Digital', 'GEN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Wintrust Financial', 'WTFC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Moog', 'MOG.A');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('First Solar', 'FSLR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Central Garden & Pet', 'CENT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Green Plains', 'GPRE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Werner Enterprises', 'WERN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AppLovin', 'APP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ITT', 'ITT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Herc Holdings', 'HRI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Gray Television', 'GTN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('IDEX', 'IEX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Boston Properties', 'BXP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pitney Bowes', 'PBI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Steelcase', 'SCS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sun Communities', 'SUI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AdaptHealth', 'AHCO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vertex Energy', 'VTNR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Genesis Energy', 'GEL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Jackson Financial', 'JXN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('FirstCash Holdings', 'FCFS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cal-Maine Foods', 'CALM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Arch Resources', 'ARCH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Avient', 'AVNT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BlueLinx Holdings', 'BXC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sinclair', 'SBGI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BOK Financial', 'BOKF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Permian Resources', 'PR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PACS Group', 'PACS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Coinbase Global', 'COIN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Western Midstream Partners', 'WES');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('G-III Apparel Group', 'GIII');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vontier', 'VNT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Matson', 'MATX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kirby', 'KEX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kaiser Aluminum', 'KALU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vista Outdoor', 'VSTO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Designer Brands', 'DBI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rollins', 'ROL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Advanced Drainage Systems', 'WMS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cinemark Holdings', 'CNK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('CrowdStrike', 'CRWD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pinterest', 'PINS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Instacart', 'CART');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hillenbrand', 'HI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Allison Transmission Holdings', 'ALSN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('RH', 'RH');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Brookdale Senior Living', 'BKD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('QuidelOrtho', 'QDEL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Trinity Industries', 'TRN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Teleflex', 'TFX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('HEICO', 'HEI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bruker', 'BRKR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Carlyle Group', 'CG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Energizer Holdings', 'ENR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Quad/Graphics', 'QUAD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Rackspace Technology', 'RXT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Waters', 'WAT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('West Pharmaceutical Services', 'WST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Carter''s', 'CRI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NeueHealth', 'NEUE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('SkyWest', 'SKYW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Acadia Healthcare', 'ACHC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Revvity', 'RVTY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Portland General Electric', 'POR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Woodward', 'WWD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('TEGNA', 'TGNA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Sabre', 'SABR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Light & Wonder', 'LNW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Vail Resorts', 'MTN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Radius Recycling', 'RDUS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PennyMac Financial Services', 'PFSI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Saia', 'SAIA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Equity Residential', 'EQR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Helmerich & Payne', 'HP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Korn Ferry', 'KFY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('PC Connection', 'CNXN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Curtiss-Wright', 'CW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('SLM', 'SLM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Benchmark Electronics', 'BHE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('American National Group', 'AEL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Pure Storage', 'PSTG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Knife River', 'KNF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Caleres', 'CAL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BrightView Holdings', 'BV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cooper-Standard Holdings', 'CPS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Primerica', 'PRI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('F5', 'FFIV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Matador Resources', 'MTDR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Snowflake', 'SNOW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Viasat', 'VSAT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('California Resources', 'CRC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Peloton Interactive', 'PTON');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Roblox', 'RBLX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Installed Building Products', 'IBP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('First National of Nebraska', 'FINN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Guess', 'GES');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ESAB', 'ESAB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AvalonBay Communities', 'AVB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('DocuSign', 'DOCU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Titan Machinery', 'TITN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ModivCare', 'MODV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hovnanian Enterprises', 'HOV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Etsy', 'ETSY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Adams Resources & Energy', 'AE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Surgery Partners', 'SGRY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Columbia Banking System', 'COLB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Verisk', 'VRSK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MasterBrand', 'MBC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Hawaiian Holdings', 'HA');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AMC Networks', 'AMCX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('SBA Communications', 'SBAC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Americold Realty Trust', 'COLD');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('NewMarket', 'NEU');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Park Hotels & Resorts', 'PK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alexandria Real Estate Equities', 'ARE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Griffon', 'GFF');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Air Lease', 'AL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('UL Solutions', 'ULS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Teradyne', 'TER');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('OGE Energy', 'OGE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Bio-Rad Laboratories', 'BIO');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Spire', 'SR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Gannett', 'GCI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Stericycle', 'SRCL');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Cullen/Frost Bankers', 'CFR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Extra Space Storage', 'EXR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('REV Group', 'REVG');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('ProFrac Holding', 'ACDC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Nordson', 'NDSN');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Summit Materials', 'SUM');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Valvoline', 'VVV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Kontoor Brands', 'KTB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Skyline Champion', 'SKY');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Teladoc Health', 'TDOC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Louisiana-Pacific', 'LPX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Universal', 'UVV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Consol Energy', 'CEIX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Playtika Holding', 'PLTK');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Alliance Resource Partners', 'ARLP');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Envista Holdings', 'NVST');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Shift4 Payments', 'FOUR');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Talen Energy', 'TLNE');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Carpenter Technology', 'CRS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('WEX', 'WEX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Old National Bancorp', 'ONB');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('AGNC Investment', 'AGNC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Wabash National', 'WNC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('MSCI', 'MSCI');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Stagwell', 'STGW');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Mativ Holdings', 'MATV');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Belden', 'BDC');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Allegiant Travel', 'ALGT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Dropbox', 'DBX');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Exact Sciences', 'EXAS');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('BWX Technologies', 'BWXT');
INSERT OR IGNORE INTO brokersystem_stock (name, symbol) VALUES ('Clear Channel Outdoor Hldgs.', 'CCO');