# Generated by Django 4.2.24 on 2025-10-01 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokersystem', '0003_alter_pricehistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=10000, max_digits=12),
        ),
    ]
