# Generated by Django 4.2.24 on 2025-10-01 09:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('brokersystem', '0002_rename_average_price_position_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricehistory',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='pricehistory',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='pricehistory',
            unique_together={('stock', 'timestamp')},
        ),
        migrations.AddIndex(
            model_name='pricehistory',
            index=models.Index(fields=['stock', '-timestamp'], name='brokersyste_stock_i_e4bf6b_idx'),
        ),
    ]
