# Generated by Django 4.2.24 on 2025-10-03 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokersystem', '0006_alter_customuser_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='current_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
