# Generated by Django 4.2.24 on 2025-09-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokersystem', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='average_price',
            new_name='price',
        ),
    ]
